spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dama_shop
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: k++BGFH4WgYDAnhwuOKhRuFIOmQsvUCNrGUr2zUIktA=
  expiration: 3600000

